// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Match1
DataFrame Match1(DataFrame df_case, DataFrame df_ctrl, String ps_var, double ps_threshold, int NumMatch);
RcppExport SEXP _IndexDate_Match1(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP ps_varSEXP, SEXP ps_thresholdSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< String >::type ps_var(ps_varSEXP);
    Rcpp::traits::input_parameter< double >::type ps_threshold(ps_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match1(df_case, df_ctrl, ps_var, ps_threshold, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// Match11
DataFrame Match11(DataFrame df_case, DataFrame df_ctrl, CharacterVector meaname, arma::vec threshold, String ID_var, String group_var, CharacterVector lab_ctrl, arma::uvec NumMatch);
RcppExport SEXP _IndexDate_Match11(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP meanameSEXP, SEXP thresholdSEXP, SEXP ID_varSEXP, SEXP group_varSEXP, SEXP lab_ctrlSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< String >::type ID_var(ID_varSEXP);
    Rcpp::traits::input_parameter< String >::type group_var(group_varSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type lab_ctrl(lab_ctrlSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match11(df_case, df_ctrl, meaname, threshold, ID_var, group_var, lab_ctrl, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// Match2
DataFrame Match2(DataFrame df_case, DataFrame df_ctrl, String ps_var, double ps_threshold, int NumMatch);
RcppExport SEXP _IndexDate_Match2(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP ps_varSEXP, SEXP ps_thresholdSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< String >::type ps_var(ps_varSEXP);
    Rcpp::traits::input_parameter< double >::type ps_threshold(ps_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match2(df_case, df_ctrl, ps_var, ps_threshold, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// Match3
DataFrame Match3(DataFrame df_case, DataFrame df_ctrl, CharacterVector meaname, NumericVector threshold, int NumMatch);
RcppExport SEXP _IndexDate_Match3(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP meanameSEXP, SEXP thresholdSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match3(df_case, df_ctrl, meaname, threshold, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// myorder_arma_2
arma::uvec myorder_arma_2(arma::mat x, arma::uvec posi, unsigned int head);
RcppExport SEXP _IndexDate_myorder_arma_2(SEXP xSEXP, SEXP posiSEXP, SEXP headSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type posi(posiSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type head(headSEXP);
    rcpp_result_gen = Rcpp::wrap(myorder_arma_2(x, posi, head));
    return rcpp_result_gen;
END_RCPP
}
// Match4
DataFrame Match4(DataFrame df_case, DataFrame df_ctrl, CharacterVector meaname, arma::vec threshold, unsigned int NumMatch);
RcppExport SEXP _IndexDate_Match4(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP meanameSEXP, SEXP thresholdSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match4(df_case, df_ctrl, meaname, threshold, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// Match41
DataFrame Match41(DataFrame df_case, DataFrame df_ctrl, String ID_var, CharacterVector meaname, arma::vec threshold);
RcppExport SEXP _IndexDate_Match41(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP ID_varSEXP, SEXP meanameSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< String >::type ID_var(ID_varSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(Match41(df_case, df_ctrl, ID_var, meaname, threshold));
    return rcpp_result_gen;
END_RCPP
}
// Match5
DataFrame Match5(DataFrame df_case, DataFrame df_ctrl, CharacterVector meaname, arma::vec threshold, unsigned int NumMatch);
RcppExport SEXP _IndexDate_Match5(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP meanameSEXP, SEXP thresholdSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match5(df_case, df_ctrl, meaname, threshold, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// Match6
DataFrame Match6(DataFrame df_case, DataFrame df_ctrl, CharacterVector meaname, NumericVector threshold, unsigned int NumMatch);
RcppExport SEXP _IndexDate_Match6(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP meanameSEXP, SEXP thresholdSEXP, SEXP NumMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NumMatch(NumMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(Match6(df_case, df_ctrl, meaname, threshold, NumMatch));
    return rcpp_result_gen;
END_RCPP
}
// Match7
DataFrame Match7(DataFrame df_case, DataFrame df_ctrl, CharacterVector meaname, arma::vec threshold, unsigned int NumMatch, int threads);
RcppExport SEXP _IndexDate_Match7(SEXP df_caseSEXP, SEXP df_ctrlSEXP, SEXP meanameSEXP, SEXP thresholdSEXP, SEXP NumMatchSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type meaname(meanameSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NumMatch(NumMatchSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(Match7(df_case, df_ctrl, meaname, threshold, NumMatch, threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _IndexDate_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// index_date
DataFrame index_date(DataFrame df_case, DataFrame df_ctrl);
RcppExport SEXP _IndexDate_index_date(SEXP df_caseSEXP, SEXP df_ctrlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    rcpp_result_gen = Rcpp::wrap(index_date(df_case, df_ctrl));
    return rcpp_result_gen;
END_RCPP
}
// index_date_1
DataFrame index_date_1(DataFrame df_case, DataFrame df_ctrl);
RcppExport SEXP _IndexDate_index_date_1(SEXP df_caseSEXP, SEXP df_ctrlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df_case(df_caseSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df_ctrl(df_ctrlSEXP);
    rcpp_result_gen = Rcpp::wrap(index_date_1(df_case, df_ctrl));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IndexDate_Match1", (DL_FUNC) &_IndexDate_Match1, 5},
    {"_IndexDate_Match11", (DL_FUNC) &_IndexDate_Match11, 8},
    {"_IndexDate_Match2", (DL_FUNC) &_IndexDate_Match2, 5},
    {"_IndexDate_Match3", (DL_FUNC) &_IndexDate_Match3, 5},
    {"_IndexDate_myorder_arma_2", (DL_FUNC) &_IndexDate_myorder_arma_2, 3},
    {"_IndexDate_Match4", (DL_FUNC) &_IndexDate_Match4, 5},
    {"_IndexDate_Match41", (DL_FUNC) &_IndexDate_Match41, 5},
    {"_IndexDate_Match5", (DL_FUNC) &_IndexDate_Match5, 5},
    {"_IndexDate_Match6", (DL_FUNC) &_IndexDate_Match6, 5},
    {"_IndexDate_Match7", (DL_FUNC) &_IndexDate_Match7, 6},
    {"_IndexDate_rcpp_hello", (DL_FUNC) &_IndexDate_rcpp_hello, 0},
    {"_IndexDate_index_date", (DL_FUNC) &_IndexDate_index_date, 2},
    {"_IndexDate_index_date_1", (DL_FUNC) &_IndexDate_index_date_1, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_IndexDate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
